### ISSUE TITLE
Box interface

### ISSUE THREAD

**Issue by awalterschulze** [Labrum/CheckIt#2]
Could you add some more verbosity to the Descriptors method.
Descriptors() (heading string,text string)
If that is what the seperate strings are for.
Lets maybe rather call it
Desc() (heading, description string)

Why am I returning time.Duration
Default() (string,time.Duration)
Rather just the default string
Default() string
Lets maybe get a better name for this method
DefaultText() string
Or lets combine it with Desc() Into
Desc() (heading, description, text string)
We could even throw Syntax in there as well.
Desc() (heading, description, text, syntax string)

You are only passing the same value back to me again.
Run(TextAreas []string, directory string, timeout time.Duration) ([]byte, error)
Rather remove it
Run(TextAreas []string, directory string) ([]byte, error)
I could just keep track of it myself.

Please keep the variables names in lower camelcase
Run(textAreas []string, directory string) ([]byte, error)

Lets keep call the directory what it is
Like runPath or sharePath, I actually don't now which it is.
I think runPath would probably be the best?
Run(textAreas []string, runPath string) ([]byte, error)

Final result

type Box interface {
  Desc() (heading, description, text, syntax string)
  Run(textAreas []string, runPath string) ([]byte, error)
}

What do you think?

**Comment by Labrum** [comment]
Yeah the interface was starting to get messy, this structure makes sense. Desc will change to your suggestion. Run will be as discussed in issue 3.
