### ISSUE TITLE
tests are failing

### ISSUE THREAD

**Issue by awalterschulze** [Labrum/CheckIt#6]
I cloned and ran go test and the test is failing.

**Comment by awalterschulze** [comment]
Maybe its time to setup a drone.io build, that checks every push for you?

**Comment by Labrum** [comment]
Test was using old signatures for Run and CombinedRun, I've update it now. Drone.io looks like a great idea. Thanks for the input.

**Comment by awalterschulze** [comment]
Tests are working :)
